on:
  workflow_dispatch:

name: Test Build Action

jobs:  
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run Build Action
      uses: 365Scores/CI-CD-dotnet-ECR-AWS@main
      with:
        project_path: ./DataServiceCore/DataServiceCore.csproj
        dockerfile_path: ./DataServiceCore/Dockerfile.github
        ecr_registry: ${{ steps.login-ecr.outputs.registry }}
        ecr_repository: ds-sandbox
        docker_tag: github-actions-test
