on:
  workflow_dispatch:

name: Test Build Action

jobs:  
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Run Build Action
      uses: 365Scores/CI-CD-dotnet-ECR-AWS@main
      with:
        project_path: ./DataServiceCore/DataServiceCore.csproj
        dockerfile_path: ./DataServiceCore/Dockerfile.github
        ecr_registry: ${{ steps.login-ecr.outputs.registry }}
        ecr_repository: ds-sandbox
        docker_tag: github-actions-test
